-- Run this in Supabase Dashboard -> SQL Editor.
-- This configures the existing public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
-- table used by the app. It does not drop the table.

CREATE TABLE IF NOT EXISTS public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Student submissions: one row per student, keyed by Firebase UID.
ALTER TABLE public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
  ADD COLUMN IF NOT EXISTS student_uid TEXT,
  ADD COLUMN IF NOT EXISTS student_email TEXT,
  ADD COLUMN IF NOT EXISTS student_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS teacher_id TEXT NOT NULL DEFAULT 'Teacher A',
  ADD COLUMN IF NOT EXISTS answers JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS comments JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
  DROP CONSTRAINT IF EXISTS v2_leadership_growth_log_status_check,
  ADD CONSTRAINT v2_leadership_growth_log_status_check
    CHECK (status IN ('draft', 'submitted', 'reviewed'));

CREATE UNIQUE INDEX IF NOT EXISTS v2_leadership_growth_log_student_uid_idx
  ON public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"(student_uid);

-- Form configuration: one row, editable by teachers.
CREATE TABLE IF NOT EXISTS public.form_config (
  id TEXT PRIMARY KEY DEFAULT 'default',
  config JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Teacher directory: editable by admins from the Admin Console.
CREATE TABLE IF NOT EXISTS public.teachers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS teachers_email_idx
  ON public.teachers (LOWER(email));

INSERT INTO public.teachers (name, email)
SELECT v.name, v.email
FROM (VALUES
  ('Mr Ridzuan',        'ridzuan@ri.edu.sg'),
  ('Ms Veronica Chua',  'veronica.chua@ri.edu.sg'),
  ('Ms Ruth Rodrigues', 'rodrigues.ruth@ri.edu.sg'),
  ('Ms Tang Mui Kee',   'muikee.tang@ri.edu.sg'),
  ('Mr Teoh Jia Yu',    'jiayu.teoh@ri.edu.sg'),
  ('Mr Ng Kar Kit',     'karkit.ng@ri.edu.sg'),
  ('Mr Sean Lee',       'cheeguan.lee@ri.edu.sg'),
  ('Mr Jason Tan',      'jason.t@ri.edu.sg'),
  ('Ms Felicia Seah',   'felicia.seah@ri.edu.sg'),
  ('Ms Leow Pey Yee',   'peyyee.leow@ri.edu.sg'),
  ('Ms Liyana',         'nurliyana.mt@ri.edu.sg'),
  ('Ms Ng Pei San',     'peisan.ng@ri.edu.sg'),
  ('Ms Arlene Low',     'arlene.chan@ri.edu.sg'),
  ('Mr Gabriel Lim',    'gabriel.lim@ri.edu.sg'),
  ('Mr Lee Chee Keong', 'cheekeong.lee@ri.edu.sg')
) AS v(name, email)
WHERE NOT EXISTS (
  SELECT 1 FROM public.teachers t WHERE LOWER(t.email) = LOWER(v.email)
);

-- Row Level Security.
ALTER TABLE public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'V2-LEADERSHIP-PROGRAMME-GROWTH-LOG'
      AND policyname = 'submissions_read_all'
  ) THEN
    CREATE POLICY "submissions_read_all"
      ON public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'V2-LEADERSHIP-PROGRAMME-GROWTH-LOG'
      AND policyname = 'submissions_insert_all'
  ) THEN
    CREATE POLICY "submissions_insert_all"
      ON public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
      FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'V2-LEADERSHIP-PROGRAMME-GROWTH-LOG'
      AND policyname = 'submissions_update_all'
  ) THEN
    CREATE POLICY "submissions_update_all"
      ON public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
      FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'V2-LEADERSHIP-PROGRAMME-GROWTH-LOG'
      AND policyname = 'submissions_delete_all'
  ) THEN
    CREATE POLICY "submissions_delete_all"
      ON public."V2-LEADERSHIP-PROGRAMME-GROWTH-LOG"
      FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'form_config'
      AND policyname = 'config_read_all'
  ) THEN
    CREATE POLICY "config_read_all"
      ON public.form_config
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'form_config'
      AND policyname = 'config_write_auth'
  ) THEN
    CREATE POLICY "config_write_auth"
      ON public.form_config
      FOR ALL USING (auth.role() = 'authenticated');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'teachers'
      AND policyname = 'teachers_read_all'
  ) THEN
    CREATE POLICY "teachers_read_all"
      ON public.teachers
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'teachers'
      AND policyname = 'teachers_write_auth'
  ) THEN
    CREATE POLICY "teachers_write_auth"
      ON public.teachers
      FOR ALL USING (auth.role() = 'authenticated');
  END IF;
END $$;

-- Teachers must exist before they can request an OTP login:
-- Supabase Dashboard -> Authentication -> Users -> Invite user.
